# Generated by Django 5.1.7 on 2026-04-26 00:12

import django.db.models.deletion
import graph.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#00d4ff', max_length=7, validators=[graph.models.validate_hex_color])),
            ],
            options={
                'db_table': 'graph_tags',
                'indexes': [models.Index(fields=['name'], name='graph_tags_name_01b60b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('z', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='nodes', to='graph.tag')),
            ],
            options={
                'db_table': 'graph_nodes',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='graph.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='graph.node')),
            ],
            options={
                'db_table': 'graph_edges',
                'indexes': [models.Index(fields=['source', 'target'], name='graph_edges_source__81a252_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='unique_edge_per_direction')],
            },
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['title'], name='graph_nodes_title_ce3e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['created_at'], name='graph_nodes_created_2a8044_idx'),
        ),
    ]
