# Generated by Django 5.1.7 on 2026-08-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
