# Generated by Django 5.1.7 on 2026-04-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_tag_node_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['source', 'target'], name='graph_edges_source__81a252_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['title'], name='graph_nodes_title_ce3e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['created_at'], name='graph_nodes_created_2a8044_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='graph_tags_name_01b60b_idx'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='unique_edge_per_direction'),
        ),
        migrations.AlterModelTable(
            name='edge',
            table='graph_edges',
        ),
        migrations.AlterModelTable(
            name='node',
            table='graph_nodes',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='graph_tags',
        ),
    ]
