# Generated by Django 5.1.7 on 2026-08-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_node_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='is_main',
        ),
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('main', 'Principal'), ('secondary', 'Secundario'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
    ]
