# Generated by Django 5.1.7 on 2026-08-20 04:08

import django.db.models.deletion
import graph.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_remove_node_is_main_node_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=graph.models.node_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='graph.node')),
            ],
            options={
                'db_table': 'graph_node_images',
                'ordering': ['-created_at'],
            },
        ),
    ]
